"""empty message

Revision ID: 351d30b199c9
Revises: d4356f63fb4e
Create Date: 2019-08-06 19:17:19.864701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '351d30b199c9'
down_revision = 'd4356f63fb4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('courses', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.drop_column('courses', 'author')
    op.add_column('user_details', sa.Column('course_id', sa.Integer(), nullable=True))
    op.add_column('user_details', sa.Column('expertise', sa.String(length=100), nullable=True))
    op.add_column('user_details', sa.Column('tutor_bio', sa.String(length=200), nullable=True))
    op.create_foreign_key(None, 'user_details', 'courses', ['course_id'], ['course_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_details', type_='foreignkey')
    op.drop_column('user_details', 'tutor_bio')
    op.drop_column('user_details', 'expertise')
    op.drop_column('user_details', 'course_id')
    op.add_column('courses', sa.Column('author', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('courses', 'start_date')
    op.drop_column('announcements', 'date')
    # ### end Alembic commands ###
