"""empty message

Revision ID: 3da6e7da8e86
Revises: e1287a290050
Create Date: 2019-07-29 14:18:32.945819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da6e7da8e86'
down_revision = 'e1287a290050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('olympiad_details', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('registered_olympiads', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registered_olympiads', 'status')
    op.drop_column('olympiad_details', 'status')
    # ### end Alembic commands ###
