"""empty message

Revision ID: 94d80d604b75
Revises: 
Create Date: 2019-07-27 16:25:31.905458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d80d604b75'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registered_courses', sa.Column('payment_done', sa.Boolean(), nullable=True))
    op.add_column('registered_events', sa.Column('payment_done', sa.Boolean(), nullable=True))
    op.add_column('registered_olympiads', sa.Column('payment_done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registered_olympiads', 'payment_done')
    op.drop_column('registered_events', 'payment_done')
    op.drop_column('registered_courses', 'payment_done')
    # ### end Alembic commands ###
