"""empty message

Revision ID: 96c0bcecb8bd
Revises: 351d30b199c9
Create Date: 2019-08-06 19:44:45.269234

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96c0bcecb8bd'
down_revision = '351d30b199c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('description', sa.String(length=600), nullable=True))
    op.drop_column('announcements', 'decription')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('decription', mysql.VARCHAR(length=600), nullable=True))
    op.drop_column('announcements', 'description')
    # ### end Alembic commands ###
