"""empty message

Revision ID: d4356f63fb4e
Revises: 3da6e7da8e86
Create Date: 2019-08-06 14:05:21.106102

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd4356f63fb4e'
down_revision = '3da6e7da8e86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('a_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('decription', sa.String(length=600), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.PrimaryKeyConstraint('a_id')
    )
    op.create_table('images',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('oly_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event_details.event_id'], ),
    sa.ForeignKeyConstraint(['oly_id'], ['olympiad_details.oly_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('progress',
    sa.Column('p_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('lecture_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['lecture_id'], ['lecture_details.lecture_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_details.user_id'], ),
    sa.PrimaryKeyConstraint('p_id')
    )
    op.create_table('schedule',
    sa.Column('s_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event_details.event_id'], ),
    sa.PrimaryKeyConstraint('s_id')
    )
    op.create_table('rel_questions_images',
    sa.Column('r_id', sa.Integer(), nullable=False),
    sa.Column('q_id', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.image_id'], ),
    sa.ForeignKeyConstraint(['q_id'], ['questions.q_id'], ),
    sa.PrimaryKeyConstraint('r_id')
    )
    op.add_column('event_details', sa.Column('venue', sa.String(length=50), nullable=True))
    op.add_column('questions', sa.Column('week_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questions', 'week', ['week_id'], ['week_id'])
    op.drop_constraint('registered_courses_ibfk_3', 'registered_courses', type_='foreignkey')
    op.drop_column('registered_courses', 'progress')
    op.add_column('user_details', sa.Column('account_type', sa.Boolean(), nullable=True))
    op.add_column('user_details', sa.Column('class_type', sa.String(length=2), nullable=True))
    op.add_column('user_details', sa.Column('instituton', sa.String(length=50), nullable=True))
    op.add_column('user_details', sa.Column('profile_pic', sa.LargeBinary(), nullable=True))
    op.add_column('user_details', sa.Column('profile_updated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_details', 'profile_updated')
    op.drop_column('user_details', 'profile_pic')
    op.drop_column('user_details', 'instituton')
    op.drop_column('user_details', 'class_type')
    op.drop_column('user_details', 'account_type')
    op.add_column('registered_courses', sa.Column('progress', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('registered_courses_ibfk_3', 'registered_courses', 'week', ['progress'], ['week_id'])
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'week_id')
    op.drop_column('event_details', 'venue')
    op.drop_table('rel_questions_images')
    op.drop_table('schedule')
    op.drop_table('progress')
    op.drop_table('images')
    op.drop_table('announcements')
    # ### end Alembic commands ###
