"""empty message

Revision ID: e1287a290050
Revises: 94d80d604b75
Create Date: 2019-07-29 09:39:09.597233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1287a290050'
down_revision = '94d80d604b75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('q_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=True),
    sa.Column('optA', sa.String(length=200), nullable=True),
    sa.Column('optB', sa.String(length=200), nullable=True),
    sa.Column('optC', sa.String(length=200), nullable=True),
    sa.Column('optD', sa.String(length=200), nullable=True),
    sa.Column('correctopt', sa.String(length=1), nullable=True),
    sa.Column('olympiad_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['olympiad_id'], ['olympiad_details.oly_id'], ),
    sa.PrimaryKeyConstraint('q_id')
    )
    op.drop_column('olympiad_details', 'questions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('olympiad_details', sa.Column('questions', mysql.VARCHAR(length=6000), nullable=True))
    op.drop_table('questions')
    # ### end Alembic commands ###
